apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: 486887731419.dkr.ecr.us-east-2.amazonaws.com/prasanth123
      ports:
        - containerPort: 8080
